# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sales.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import locale

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1089, 754)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 100, 271, 141))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(320, 100, 251, 141))
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 310, 261, 141))
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.get_sales)

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 500, 281, 161))
        self.label_2.setObjectName("label_2")
        self.label_monthly_sales = QtWidgets.QLabel(self.centralwidget)
        self.label_monthly_sales.setGeometry(QtCore.QRect(330, 500, 271, 141))
        self.label_monthly_sales.setText("")
        self.label_monthly_sales.setObjectName("label_monthly_sales")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1089, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #took pic of it
        self.months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]


        #add months to combo box
        self.comboBox.addItems(self.months)

        #Create a list with all sales data
        self.sales_data =[2345,4567,7890,5678,3456,1235,6789,4567,7890,3456,6789]



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Month"))
        self.pushButton.setText(_translate("MainWindow", "Get Sales"))
        self.label_2.setText(_translate("MainWindow", "Monthly Sales"))


    def get_sales(self):

        #get month selected by user from the combo box
        current_month = self.comboBox.currentText()
        print("Month selected by the user", current_month)

        for index, element in enumerate(self.months):
            print(index, element) #get the index and month value in the iteration

            if element == current_month: #if iterated month is same as chosen by the user
                print("Found selected month", self.sales_data[index])#print sales data
                self.label_monthly_sales.setText(str(self.sales_data[index]))#show sales data for chosen month


                locale.setlocale(locale.LC_ALL, "English_United States.1252")
                print(locale.currency(self.sales_data[index], grouping=True))
                self.label_monthly_sales.setText(str(locale.currency(self.sales_data[index], grouping=True)))


if __name__ == '__main__':
    import sys
    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec_())