# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student_records_dictionary_add_update_delete_tabs_inclass.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 763)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 551, 711))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.lineEdit_add_id = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_add_id.setGeometry(QtCore.QRect(290, 50, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_add_id.setFont(font)
        self.lineEdit_add_id.setObjectName("lineEdit_add_id")
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setGeometry(QtCore.QRect(10, 50, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setGeometry(QtCore.QRect(10, 220, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_1)
        self.label_4.setGeometry(QtCore.QRect(10, 290, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_add_fname = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_add_fname.setGeometry(QtCore.QRect(290, 140, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_add_fname.setFont(font)
        self.lineEdit_add_fname.setObjectName("lineEdit_add_fname")
        self.lineEdit_add_lname = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_add_lname.setGeometry(QtCore.QRect(290, 220, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_add_lname.setFont(font)
        self.lineEdit_add_lname.setObjectName("lineEdit_add_lname")
        self.lineEdit_add_gpa = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_add_gpa.setGeometry(QtCore.QRect(290, 300, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_add_gpa.setFont(font)
        self.lineEdit_add_gpa.setObjectName("lineEdit_add_gpa")
        self.pushButton_add_clear = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_add_clear.setGeometry(QtCore.QRect(10, 440, 241, 61))
        self.pushButton_add_clear.setObjectName("pushButton_add_clear")

        #When pushed clears all add line edits
        self.pushButton_add_clear.clicked.connect(self.clear_add)

        self.pushButton_add_record = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_add_record.setGeometry(QtCore.QRect(290, 440, 241, 61))
        self.pushButton_add_record.setObjectName("pushButton_add_record")

        # method to add records to the dictionary
        self.pushButton_add_record.clicked.connect(self.add_records)

        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_update_clear = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_update_clear.setGeometry(QtCore.QRect(10, 410, 241, 61))
        self.pushButton_update_clear.setObjectName("pushButton_update_clear")

        # When pushed clears all update line edits
        self.pushButton_update_clear.clicked.connect(self.clear_update)

        self.lineEdit_update_id = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_update_id.setGeometry(QtCore.QRect(290, 20, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_update_id.setFont(font)
        self.lineEdit_update_id.setObjectName("lineEdit_update_id")
        self.pushButton_update_record = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_update_record.setGeometry(QtCore.QRect(290, 410, 241, 61))
        self.pushButton_update_record.setObjectName("pushButton_update_record")

        # method when update record is clicked
        self.pushButton_update_record.clicked.connect(self.update_records)

        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 260, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_update_gpa = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_update_gpa.setGeometry(QtCore.QRect(290, 270, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_update_gpa.setFont(font)
        self.lineEdit_update_gpa.setObjectName("lineEdit_update_gpa")
        self.lineEdit_update_lname = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_update_lname.setGeometry(QtCore.QRect(290, 190, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_update_lname.setFont(font)
        self.lineEdit_update_lname.setObjectName("lineEdit_update_lname")
        self.lineEdit_update_fname = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_update_fname.setGeometry(QtCore.QRect(290, 110, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_update_fname.setFont(font)
        self.lineEdit_update_fname.setObjectName("lineEdit_update_fname")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit_delete_fname = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_delete_fname.setGeometry(QtCore.QRect(290, 110, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_delete_fname.setFont(font)
        self.lineEdit_delete_fname.setObjectName("lineEdit_delete_fname")
        self.pushButton_delete_record = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_delete_record.setGeometry(QtCore.QRect(290, 410, 241, 61))
        self.pushButton_delete_record.setObjectName("pushButton_delete_record")

        #When pushButton_delete_record is clicked it connects to the function delete_records
        self.pushButton_delete_record.clicked.connect(self.delete_records)

        self.lineEdit_delete_id = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_delete_id.setGeometry(QtCore.QRect(290, 20, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_delete_id.setFont(font)
        self.lineEdit_delete_id.setObjectName("lineEdit_delete_id")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(10, 260, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_delete_gpa = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_delete_gpa.setGeometry(QtCore.QRect(290, 270, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_delete_gpa.setFont(font)
        self.lineEdit_delete_gpa.setObjectName("lineEdit_delete_gpa")
        self.pushButton_delete_clear = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_delete_clear.setGeometry(QtCore.QRect(10, 410, 241, 61))
        self.pushButton_delete_clear.setObjectName("pushButton_delete_clear")

        # When pushed clears all delete line edits
        self.pushButton_delete_clear.clicked.connect(self.clear_delete)

        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit_delete_lname = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_delete_lname.setGeometry(QtCore.QRect(290, 190, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_delete_lname.setFont(font)
        self.lineEdit_delete_lname.setObjectName("lineEdit_delete_lname")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(10, 110, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(10, 190, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab_3, "")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(570, 40, 541, 691))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # create a dictionary to hold student records
        # format will be as follows
        # student_id:{'id':student_id,'fname':first_name,'lname':last_name,'gpa':student_gpa}

        self.records = {}






    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Student ID"))
        self.label_2.setText(_translate("MainWindow", "First Name"))
        self.label_3.setText(_translate("MainWindow", "Last Name"))
        self.label_4.setText(_translate("MainWindow", "GPA"))
        self.pushButton_add_clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_add_record.setText(_translate("MainWindow", "Add Record"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Add Student Record"))
        self.pushButton_update_clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_update_record.setText(_translate("MainWindow", "Update Record"))
        self.label_5.setText(_translate("MainWindow", "GPA"))
        self.label_6.setText(_translate("MainWindow", "First Name"))
        self.label_7.setText(_translate("MainWindow", "Last Name"))
        self.label_8.setText(_translate("MainWindow", "Student ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Update Student Record"))
        self.pushButton_delete_record.setText(_translate("MainWindow", "Delete Record"))
        self.label_9.setText(_translate("MainWindow", "GPA"))
        self.pushButton_delete_clear.setText(_translate("MainWindow", "Clear"))
        self.label_12.setText(_translate("MainWindow", "Student ID"))
        self.label_10.setText(_translate("MainWindow", "First Name"))
        self.label_11.setText(_translate("MainWindow", "Last Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Delete Student Record"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Student ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "GPA"))

    # add records to the dictionary
    def add_records(self):  # 1 usage
        print("in add_records function")

        # check if student ID exists in the records
        if self.lineEdit_add_id.text() in self.records:
            msg = QtWidgets.QMessageBox()
            msg.setText("Student id already exists")
            msg.exec_()

        # student ID does not exist
        else:
            print("print the dictionary as is", self.records)
            # add student_id from the UI form as a new key; value associated is a dictionary that holds id, fname, lname, gpa
            self.records[self.lineEdit_add_id.text()] = {}

            self.records[self.lineEdit_add_id.text()]['id'] = self.lineEdit_add_id.text()
            self.records[self.lineEdit_add_id.text()]['fname'] = self.lineEdit_add_fname.text()
            self.records[self.lineEdit_add_id.text()]['lname'] = self.lineEdit_add_lname.text()
            self.records[self.lineEdit_add_id.text()]['gpa'] = self.lineEdit_add_gpa.text()

            print("print the dictionary after adding record", self.records)
            self.display_records()

    def display_records(self):  # 1 usage
        self.tableWidget.setRowCount(0)  # make sure everytime the show-data button is clicked, no rows exist

        # iterate over the dictionary to access each student record one at a time
        for id, student in self.records.items():
            # get current row_count of the table
            row = self.tableWidget.rowCount()
            # insert a new row in the table
            self.tableWidget.insertRow(row)
            # column 1 - student id
            self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(student['id']))
            # column 2 - fname
            self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(student['fname']))
            # column 3 - lname
            self.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(student['lname']))
            # column 4 - gpa --> needs string so convert float to string
            self.tableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(str(student['gpa'])))

    def update_records(self):  # 1 usage

        # update only if student id exists
        if self.lineEdit_update_id.text() in self.records:

            print("in update_records function")
            self.records[self.lineEdit_update_id.text()]['id'] = self.lineEdit_update_id.text()
            self.records[self.lineEdit_update_id.text()]['fname'] = self.lineEdit_update_fname.text()
            self.records[self.lineEdit_update_id.text()]['lname'] = self.lineEdit_update_lname.text()
            self.records[self.lineEdit_update_id.text()]['gpa'] = self.lineEdit_update_gpa.text()
            self.display_records()

    def delete_records(self):  # 1 usage
        # delete key-value pair for student with id entered by the user
        del self.records[self.lineEdit_delete_id.text()]
        self.display_records()

    def clear_add(self):
        self.lineEdit_add_id.clear()
        self.lineEdit_add_fname.clear()
        self.lineEdit_add_lname.clear()
        self.lineEdit_add_gpa.clear()

    def clear_update(self):
        self.lineEdit_update_id.clear()
        self.lineEdit_update_fname.clear()
        self.lineEdit_update_lname.clear()
        self.lineEdit_update_gpa.clear()

    def clear_delete(self):
        self.lineEdit_delete_id.clear()
        self.lineEdit_delete_fname.clear()
        self.lineEdit_delete_lname.clear()
        self.lineEdit_delete_gpa.clear()


if __name__ == '__main__':
    import sys
    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec_())