# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Student.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 754)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 261, 141))
        self.pushButton.setObjectName("pushButton")

        #When pushButton is clicked it connects to the function show_data
        self.pushButton.clicked.connect(self.show_data)

        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(480, 30, 571, 691))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1075, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # self.records[1]['id']
        # self.records[1]['fname']
        # self.records[1]['lname']
        # self.records[1]['gpa']
        self.records = {
            1: {'id': 1, 'fname': 'Bob', 'lname': 'Jones', 'gpa': 3.8},
            2: {'id': 2, 'fname': 'Alice', 'lname': 'Ware', 'gpa': 3.9},
            3: {'id': 3, 'fname': 'Tony', 'lname': 'Vance', 'gpa': 3.5},
            4: {'id': 4, 'fname': 'Nancy', 'lname': 'Jones', 'gpa': 3.6},
            5: {'id': 5, 'fname': 'Bob', 'lname': 'Jones', 'gpa': 3.5}
        }



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Show Data"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Student_ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "First_Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last_Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Connect_GPA"))

    # code for populating data in the table_widget
    def show_data(self):  # 1 usage

        self.tableWidget.setRowCount(0)  # make sure everytime the show-data button is clicked, no rows exist

        # iterate over the dictionary to access each student record one at a time
        for id, student in self.records.items():
            print(id,student,student['id'],student['fname'],student['lname'],student['gpa'])

            # get current row_count of the table
            row = self.tableWidget.rowCount()

            # insert a new row in the table
            self.tableWidget.insertRow(row)

            print("Added row to the table", row)

            # column 1 - student id
            self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(student['id']))

            # column 2 - fname
            self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(student['fname']))

            # column 3 - lname
            self.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(student['lname']))

            # column 4 - gpa --> needs string so convert float to string
            self.tableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(str(student['gpa'])))


if __name__ == '__main__':
    import sys
    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec_())