# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'unityidgen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fnamelabel = QtWidgets.QLabel(self.centralwidget)
        self.fnamelabel.setGeometry(QtCore.QRect(60, 50, 121, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fnamelabel.setFont(font)
        self.fnamelabel.setObjectName("fnamelabel")
        self.mnamelabel = QtWidgets.QLabel(self.centralwidget)
        self.mnamelabel.setGeometry(QtCore.QRect(60, 140, 121, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mnamelabel.setFont(font)
        self.mnamelabel.setObjectName("mnamelabel")
        self.lnamelabel = QtWidgets.QLabel(self.centralwidget)
        self.lnamelabel.setGeometry(QtCore.QRect(50, 240, 121, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lnamelabel.setFont(font)
        self.lnamelabel.setObjectName("lnamelabel")
        self.fnameinput = QtWidgets.QLineEdit(self.centralwidget)
        self.fnameinput.setGeometry(QtCore.QRect(210, 79, 121, 31))
        self.fnameinput.setObjectName("fnameinput")
        self.mnameinput = QtWidgets.QLineEdit(self.centralwidget)
        self.mnameinput.setGeometry(QtCore.QRect(210, 169, 121, 31))
        self.mnameinput.setObjectName("mnameinput")
        self.lnameinput = QtWidgets.QLineEdit(self.centralwidget)
        self.lnameinput.setGeometry(QtCore.QRect(210, 269, 121, 31))
        self.lnameinput.setObjectName("lnameinput")
        self.genunityid = QtWidgets.QPushButton(self.centralwidget)
        self.genunityid.setGeometry(QtCore.QRect(50, 370, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.genunityid.setFont(font)
        self.genunityid.setObjectName("genunityid")

        #Generates the code in def(genuintyid)
        self.genunityid.clicked.connect(self.generate_unity)

        self.clearbutton = QtWidgets.QPushButton(self.centralwidget)
        self.clearbutton.setGeometry(QtCore.QRect(240, 370, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.clearbutton.setFont(font)
        self.clearbutton.setObjectName("clearbutton")

        #in class we added when clicked clears all
        self.clearbutton.clicked.connect(self.clear)

        self.exitbutton = QtWidgets.QPushButton(self.centralwidget)
        self.exitbutton.setGeometry(QtCore.QRect(440, 370, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.exitbutton.setFont(font)
        self.exitbutton.setObjectName("exitbutton")

        #In class we added exceutes exit function
        self.exitbutton.clicked.connect(self.exit)

        self.unityidlabel = QtWidgets.QLabel(self.centralwidget)
        self.unityidlabel.setGeometry(QtCore.QRect(50, 460, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.unityidlabel.setFont(font)
        self.unityidlabel.setObjectName("unityidlabel")
        self.unityidlabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.unityidlabel_2.setGeometry(QtCore.QRect(240, 460, 171, 51))
        self.unityidlabel_2.setText("")
        self.unityidlabel_2.setObjectName("unityidlabel_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 709, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fnamelabel.setText(_translate("MainWindow", "First Name"))
        self.mnamelabel.setText(_translate("MainWindow", "Middle Name"))
        self.lnamelabel.setText(_translate("MainWindow", "Last Name"))
        self.genunityid.setText(_translate("MainWindow", "Generate UNITY ID"))
        self.clearbutton.setText(_translate("MainWindow", "Clear"))
        self.exitbutton.setText(_translate("MainWindow", "Exit"))
        self.unityidlabel.setText(_translate("MainWindow", "UNITY ID"))

    #clear all inputs in application
    def clear(self):
        self.fnameinput.clear() #clears the fname of user input
        self.mnameinput.clear() # clears the mname of user input
        self.lnameinput.clear() #clears the lname of user input

#exit application
    def exit(self):
        application.exit_() #Exits the application

    def generate_unity(self):
        #accept first name
        fname = self.fnameinput.text().lower().strip()
        print("First name from the UI form:", fname)
        #accept middle name
        mname = self.mnameinput.text().lower().strip()
        print("Middle name from the UI form:", mname)
        #accept last name
        lname = self.lnameinput.text().lower().strip()
        print("Last name from the UI form:", lname)
        #get the first character of fname and mname; first 6 characters of lname
        fname = fname[0]
        mname = mname[0]
        lname = lname[0:6]

        unityid = fname+mname+lname
        print("UNITY ID:", unityid)

        self.unityidlabel_2.setText(unityid)

if __name__ == '__main__':
    import sys
    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec_())